// Centralized field options for all forms
const fieldOptions = {
  'Speaker Applications': {
    'Industry': [
      'Agriculture & Food',
      'Arts and Cultures',
      'Business / Management',
      'Consulting',
      'Education',
      'Energy and Mining',
      'Finance & Banking',
      'Government & Public Policy',
      'Healthcare & Medical',
      'IT & AI',
      'Legal Services',
      'Manufacturing',
      'Media & Entertainment',
      'Non Profit and NGO',
      'Others',
      'Real Estate & Construction',
      'Research and Development',
      'Retail and Consumer Goods',
      'Technology',
      'Telecommunications',
      'Tourism & Hospitality',
      'Transport & Logistics'
    ],
    'Years Experience': [
      '1-3 years',
      '4-5 years',
      '5-10 years',
      '10-15 years',
      '15-20 years',
      '20-25 years',
      '25 years +'
    ],
    'Speaking Experience': [
      'Beginner',
      'Intermediate',
      'Advanced',
      'Expert'
    ],
    'Number of Events': [
      '1-5 events',
      '6-10 events',
      '11-20 events',
      '21-50 events',
      '51-100 events',
      '100 - 500',
      '500+'
    ],
    'Largest Audience': [
      '1-50',
      '51-200',
      '201-500',
      '500 - 1000',
      '1000 - 5000',
      '5000+'
    ],
    'Virtual Experience': [
      'None',
      'Limited',
      'Moderate',
      'Extensive',
      'Experienced'
    ],
    'Travel Willingness': [
      'Virtual Only',
      'Local Only',
      'Domestic',
      'International',
      'On request'
    ],
    'Country': [
      'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria',
      'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
      'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia',
      'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo (Congo-Brazzaville)',
      'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia (Czech Republic)', 'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
      'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini (fmr. "Swaziland")',
      'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
      'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq',
      'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia',
      'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
      'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro',
      'Morocco', 'Mozambique', 'Myanmar (formerly Burma)', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger',
      'Nigeria', 'North Korea', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestine State', 'Panama', 'Papua New Guinea',
      'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia',
      'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles',
      'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain',
      'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga',
      'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
      'United States of America', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe', 'USA / South Africa'
    ],
    'Expertise Level': [
      'Entry Level',
      'Mid Level',
      'Senior Level',
      'Executive Level',
      'C-Suite',
      'Board Level',
      'International Renown Expert',
      'International Renown Trainer',
      'Celebrity'
    ],
    'Spoken Languages': [
      'English', 'French', 'German', 'Dutch', 'Spanish', 'Portuguese', 'Russian', 'Chinese', 'Hindi', 'Arabic', 'Swahili', 'Amharic', 'Yoruba', 'Zulu', 'Afrikaans', 'isiXhosa', 'Others', 'Sepedi'
    ],
    'Target Audience': [
      'Board of Directors / Board Committees',
      'C-Suite / Executive Leadership Team',
      'Development / NGO / Multilateral Teams',
      'Energy / Mining Teams',
      'Entrepreneurs / SMEs & Startups',
      'Finance / Strategy',
      'Frontline Staff / Operators',
      'Frontline Supervisors',
      'Government Executives / Public Sector Leaders',
      'Healthcare Professionals',
      'High-Potentials / Emerging Leaders (HiPo)',
      'HR / People & Culture',
      'Marketing / Brand / Comms / CX',
      'Middle Management (People Managers)',
      'Municipal / Local Government Leaders',
      'Operations / Supply Chain / PMO',
      'Product / Engineering / Tech & Data',
      'Sales Organisation (AEs, SEs, CS, Partners)',
      'Senior Leaders (VP/Director)',
      'Universities / Business Schools / Educators',
      'Women in Leadership (ERGs / Networks)',
      'Youth / Graduates / Early Career'
    ],
    'Delivery Context': [
      'Annual Leadership Conference / Town Hall',
      'Boardroom Advisory / Consulting',
      'Coaching (1:1 / Team)',
      'Executive Briefing Centre / External Organiser',
      'Executive Leadership Programme / Academy Cohort',
      'Executive Offsite / Senior Getaway',
      'Fireside',
      'Frontline / Lower-Management Training',
      'Keynote / Plenary',
      'Masterclass',
      'Middle-Management Training (in-house)',
      'Moderation',
      'Panel',
      'Sales Kickoff / Sales Enablement (SKO)',
      'Strategy Session',
      'Succession / HiPo / OD Track',
      'Virtual Webinar / Studio',
      'Workshop / Masterclass'
    ],
    'Fee Range Local': [
      '$500-$1 000',
      '$1 000-$2 500',
      '$2 500-$5 000',
      '$5 0000- $10 000',
      '$10 000 - $25 000',
      '$25 000 - $50 000',
      '$50 000 - $100 000',
      '$100 000+',
      'On request (TBD)',
      'On request',
      '$$$',
      '$$$$',
      '$$$$$'
    ],
    'Fee Range Continental': [
      '$500-$1 000',
      '$1 000-$2 500',
      '$2 500-$5 000',
      '$5 000- $10 000',
      '$10 000 - $25 000',
      '$25 000 - $50 000',
      '$50 000 - $100 000',
      '$100 000+',
      'On request (TBD)',
      'On request'
    ],
    'Fee Range International': [
      '$500-$1 000',
      '$1 000-$2 500',
      '$2 500-$5 000',
      '$5 000- $10 000',
      '$10 000- $25 000',
      '$25 000 - $50 000',
      '$50 000 - $100 000',
      '$100 000+',
      'On request (TBD)',
      'On request'
    ],
    'Fee Range Virtual': [
      '$500-$1 000',
      '$1 000-$2 500',
      '$2 500-$5 000',
      '$5 000- $10 000',
      '$10 000 - $25 000',
      '$25 000 - $50 000',
      '$50 000 - $100 000',
      '$100 000+',
      'On request (TBD)',
      'On request'
    ],
    'Fee Range General': [
      '$',
      '$$',
      '$$$',
      '$$$$',
      '$$$$$',
      'On Request'
    ]
  },
  'Client Inquiries': {
    'Company Size': [
      '1 - 10 employees',
      '11 - 50 employees',
      '51 - 250 employees',
      '251 - 500 employees',
      '501 - 1000 employees',
      '1000 + employees'
    ],
    'Industry': [
      'Technology',
      'Finance & Banking',
      'Healthcare & Medical',
      'Education',
      'Government & Public Policy',
      'Non Profit and NGO',
      'Energy and Mining',
      'Agriculture & Food',
      'Manufacturing',
      'Telecommunications',
      'Transport & Logistics',
      'Real Estate & Construction',
      'Media & Entertainment',
      'Tourism & Hospitality',
      'Retail and Consumer Goods',
      'Legal Services',
      'Consulting',
      'Research and Development',
      'Arts and Cultures',
      'IT & AI',
      'Others'
    ],
    'Audience Size': [
      'Less than 50',
      '50-100',
      '100-500',
      '500-1000',
      'More than 1000'
    ],
    'Budget Range': [
      'Less than $1 000 / R20 000',
      '$1 000-$2 500 / R20 000 - R50 000',
      '$2 500-$5 000 / R50000 - R100 000',
      '$5 000 - $10 000 / R100 000 - R200 000',
      'More than $10 000 / R200 000'
    ],
    'Presentation Format': [
      'In-Person',
      'Virtual',
      'Hybrid'
    ],
    'Focus Area': [
      'TBD - Not sure yet',
      'Board of Directors / Board Committees',
      'C-Suite / Executive Leadership Team',
      'Development / NGO / Multilateral Teams',
      'Energy / Mining Teams',
      'Entrepreneurs / SMEs & Startups',
      'Finance / Strategy',
      'Frontline Staff / Operators',
      'Frontline Supervisors',
      'Government Executives / Public Sector Leaders',
      'Healthcare Professionals',
      'High-Potentials / Emerging Leaders (HiPo)',
      'HR / People & Culture',
      'Marketing / Brand / Comms / CX',
      'Middle Management (People Managers)',
      'Municipal / Local Government Leaders',
      'Operations / Supply Chain / PMO',
      'Others',
      'Product / Engineering / Tech & Data',
      'Sales Organisation (AEs, SEs, CS, Partners)',
      'Senior Leaders (VP/Director)',
      'Universities / Business Schools / Educators',
      'Women in Leadership (ERGs / Networks)',
      'Youth / Graduates / Early Career'
    ],
    'Format': [
      'TBD - Not sure yet',
      'Annual Leadership Conference / Town Hall',
      'Boardroom Advisory / Consulting',
      'Coaching (1:1 / Team)',
      'Executive Briefing Centre / External Organiser',
      'Executive Leadership Programme / Academy Cohort',
      'Executive Offsite / Senior Getaway',
      'Fireside',
      'Frontline / Lower-Management Training',
      'Keynote / Plenary',
      'Masterclass',
      'Middle-Management Training (in-house)',
      'Moderation',
      'Panel',
      'Sales Kickoff / Sales Enablement (SKO)',
      'Succession / HiPo / OD Track',
      'Virtual Webinar / Studio',
      'Others'
    ]
  },
  'Quick Inquiries': {
    // Quick inquiries typically don't have dropdown fields
    // but we can add them here if needed in the future
  }
}

export default fieldOptions

